### ISSUE TITLE
Update to 1.17

### ISSUE THREAD

**Issue by ChrissW-R1** [Phiwa/DragonTravel#77]
I tried to use this plugin with Minecraft 1.17 (PaperMC 1.17 Build 34).

```
[Server thread/ERROR]: [DragonTravel] Could not register RyeDragon entity.
       Version 'v1_17_R1' is currently not supported.
       ----------------------------------------------------------
[Server thread/WARN]: java.lang.ClassNotFoundException: eu.phiwa.dragontravel.nms.v1_17_R1.EntityRegister
[Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
[Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[Server thread/WARN]: 	at eu.phiwa.dragontravel.core.hooks.server.NMSHandler.getEntityRegister(NMSHandler.java:57)
[Server thread/WARN]: 	at eu.phiwa.dragontravel.core.DragonTravel.onLoad(DragonTravel.java:112)
[Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:399)
[Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:275)
[Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118)
[Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[Server thread/ERROR]: ----------------------------------------------------------
[Server thread/ERROR]: [org.bukkit.craftbukkit.v1_17_R1.CraftServer] Cannot invoke "eu.phiwa.dragontravel.core.hooks.server.IEntityRegister.registerEntity()" because "this.entityRegister" is null initializing DragonTravel v01.007.11 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "eu.phiwa.dragontravel.core.hooks.server.IEntityRegister.registerEntity()" because "this.entityRegister" is null
	at eu.phiwa.dragontravel.core.DragonTravel.onLoad(DragonTravel.java:116) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:399) ~[patched_1.17.jar:git-Paper-"f110140"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:275) ~[patched_1.17.jar:git-Paper-"f110140"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-"f110140"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"f110140"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Phiwa** [comment]
Thanks for opening this issue.
I'll take a look at it tomorrow and see if the update is easy or requires additional work.

**Comment by Phiwa** [comment]
Sadly, it looks like there were big changes introduced with Minecraft 1.17 and Spigot 1.17.

1. Minecraft now requires Java 16
2. There were some changes done to the obfuscation in Spigot which means that NMS code (that's how DragonTravel implements the custom dragons) probably needs some big refactoring.

_Source: https://www.spigotmc.org/threads/spigot-bungeecord-1-17.510208/_

Since I barely found any time to work on DragonTravel in the last year and I do not see how this could change in the nearer future, I'm not sure if DragonTravel will be available for Minecraft/Spigot 1.17+.

⚠️⚠️⚠️ **If there is anybody who is willing to look into the necessary changes and create a pull request: You are more than welcome to do so!**

I'm really sorry that after nearly ten years of work on DragonTravel, I will no longer be able to maintain it without contributions from other developers, but I simply do not have the time anymore... 😢

**Comment by bmack94** [comment]
I have "fixed" it for the 1.17 only (i have removed the support for older versions).
https://github.com/bmack94/DragonTravel

Please be aware that im not a Developer and my coding skills especially in Java are really bad.

For everyone who needs it you can clone the Repo and do a mvn compile, you will get a jar in the target dir.

**Comment by bmack94** [comment]
i refactored my code and so on, see PR: #78

**Comment by Phiwa** [comment]
Thanks again for the contribution @bmack94 !

Version 01.008.01 has been uploaded to BukkitDev and will be available after review.
